version: "3.7"
services:
  spark-master:
    image: datadrone/spark-master:3.1.1-hadoop3.2-rapids
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ${PWD}/spark_apps:/opt/spark-apps
       - ${PWD}/data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "PYSPARK_PYTHON=/usr/bin/python3"
      - "PYSPARK_DRIVER_PYTHON=/usr/bin/python3"
  spark-worker-1:
    image: datadrone/spark-worker:3.1.1-hadoop3.2-rapids
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=16
      - SPARK_WORKER_MEMORY=32G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
      - SPARK_WORKER_OPTS=-Dspark.worker.resource.gpu.amount=2 -Dspark.worker.resource.gpu.discoveryScript=/opt/sparkRapidsPlugin/getGpusResources.sh
      - "PYSPARK_PYTHON=/usr/bin/python3"
      - "PYSPARK_DRIVER_PYTHON=/usr/bin/python3"
    volumes:
       - ${PWD}/apps:/opt/spark-apps
       - ${PWD}/data:/opt/spark-data
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1']
            capabilities: [gpu, utility, compute]
  notebook:
    #build: docker/
    image: datadrone/spark_notebook:3.1.1-hadoop3.2
    ports:
      - "9200:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JAVA_HOME=/usr
      - SPARK_MASTER=spark://spark-master:7077
      - "PYSPARK_PYTHON=/usr/bin/python3"
      - "PYSPARK_DRIVER_PYTHON=/usr/bin/python3"
    ipc: host
    volumes:
       - /home/brian/Workspace:/home/jovyan/work
       - ${PWD}/data:/opt/spark-data
